[project]
name = "boot-template-plugin"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "mJehanno", email = "mathob.jehanno@hotmail.fr" }
]
dependencies = [
    "jinja2>=3.1.5",
    "extism-sys>=1.9.1",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.rye.scripts]
wasm = {cmd = "extism-py ./src/boot_template_plugin/__init__.py -o plugin.wasm", env = {PYTHONPATH= "/home/egmar/Documents/projects/boot-template-plugin/.venv/lib/python3.12/site-packages"} }

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/boot_template_plugin"]
